### ISSUE TITLE
Automate conda-pack process somehow?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-yarn#3]
Should we be willing to package up the user's current environment with conda pack if they don't specify anything?

**Comment by jcrist** [comment]
I'm against doing this, because:

- conda isn't a requirement for dask-yarn, other ways of distributing environments work fine
- Users really should think about their worker environments, to ensure they have the proper packages installed on each node
- This (can be) a rather expensive operation to do automatically.

**Comment by jcrist** [comment]
Closing based on the reasoning above. Can be reopened as needed.
