### ISSUE TITLE
[question] Dask yarn strategy for available resource utilization on EMR

### ISSUE THREAD

**Issue by manugarri** [dask/dask-yarn#63]
I am working on using dask yarn on EMR using ephemeral clusters. As such, I would like to use the cluster resources at their maximum.

However, I am struggling to get dask to  use more than 50 % of the cores. I understand that like with any yarn app, I can specify the resources my app wants. However this logic doesnt really make sense in the context of single app, ephemeral tasks. Since there is only one app running on a cluster designed for it, it should use all of the available resources.

Is there any way to create a yarn cluster such that it uses all of the available resources? I apologize if this is somewhat documented but havent been able to find it in the docs.

**Comment by jcrist** [comment]
This is possible (I've done it), but isn't super straightforward due to limitations with YARN/EMR. This basically becomes a manual tiling problem where you need to compute the number and size of workers to fully use the whole EMR cluster. This is complicated due to the following:

- YARN itself takes some of the resources from each node. I haven't used EMR in a while (since I wrote the docs), but IIRC the resources on the EMR console are correct while the resources specified in the AWS instance type are slightly larger.
- Besides the workers, an additional process (the "Application Master") also runs on the cluster - this takes 512 MiB and 1 core by default.

If you have nodes composed of 4 cores and 6 GiB each and you ask for workers with 2 cores and 4 GiB each, each node will reach capacity with only a single worker (there's not enough resources on each node to run an additional worker). So you'll need to figure out how to select worker size so that you don't end up with extra unused space.

**Comment by jcrist** [comment]
@manugarri any update here?

**Comment by manugarri** [comment]
hey @jcrist , as I wrote in another issue i just had a baby and im on parental leave. If you want let's close  the issue and I will reopen it if necessary. Thank you!

**Comment by jcrist** [comment]
No worries, thanks for the update and congratulations! I'll close this for now, feel free to reopen if you still have questions when you get back.

**Comment by AlJohri** [comment]
I actually was wondering if it could be possible to add a simple configuration similar to spark's `maximizeResourceAllocation`?

I think it's possible to get the memory/vcpus from the instance metadata
