### ISSUE TITLE
client.upload_file() fails unless we use time.sleep

### ISSUE THREAD

**Issue by crleblanc** [dask/dask-yarn#65]
Hi,

I am having issues with client.upload_file() when using a YarnCluster on a Spark EMR in AWS (one worker node).  I've managed to find a workaround hack of using time.sleep() before creating a client from the cluster.

Without this sleep the upload_file() function appears to work but sys.path on the worker is not updated to include the zipfile I uploaded.  This causes a ModuleNotFoundError exception in the function passed to client.submit().

I've created a minimal gist that shows this issue, at least on the EMR Spark cluster I'm using on AWS.  I'm running this command on the master node using Python 3.6 (EMR 5.23.0): https://gist.github.com/crleblanc/ff4b7860a8a0401d283f7077c0d8953c.  Setting WAIT_SECS to 0 causes this script to fail.  Setting this to a large value like 10 seconds causes this example to pass as expected.

I have a bootstrap script that installs all of my dependencies but we're using upload_file() for code that changes often.  This tends to change on every new instance of the cluster.

Hopefully this gist gives you an idea of where to investigate.  Thanks for your work on such an excellent project!

**Comment by jcrist** [comment]
Apologies for the slow response here. The issue is that `scale` is a non-blocking operation. It schedules two new workers to be added to the cluster, but doesn't wait for them to be up. If you add:

```
Client.wait_for_workers(2)
```

before calling `upload_file`, that would work. The downside with this approach is that it the files won't be added to workers that are added later (e.g. if you scale up your cluster later). 

A more complicated, but also more robust approach would be to use a worker plugin (http://distributed.dask.org/en/latest/api.html#distributed.Client.register_worker_callbacks) to download code on worker startup. These are run for all existing and future workers, but would require you to write a function like:

```python
def download_code_and_add_to_python_path():
    ...
client.register_worker_callbacks(setup=download_code_and_add_to_python_path)
```

Note that both of these features are only on the master branch of distributed, and haven't been released yet. If you want to try them out, you can install like:

```
pip install git+https://github.com/dask/distributed.git
```

Alternatively, you could do a less efficient but still sufficient wait using the current release:

```python
def wait_for_workers(client, n):
    while not client.scheduler_info()['workers'] >= n:
        time.sleep(0.25)
```

**Comment by crleblanc** [comment]
Thanks for the info Jim, those sound like excellent suggestion.

We're making heavy use of PySpark at the moment so I managed to solve my problem by switching to a pandas_udf.  They're simple but fairly restrictive.  We may look at Dask again if pandas_udfs don't give us enough flexibility.
